# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2

defaults: &defaults
  working_directory: ~/guildatech
  docker:
    - image: cimg/elixir:1.11.3
      environment:
        MIX_ENV: test

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-build-cache-{{ checksum "mix.lock" }}
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --all-warnings --warnings-as-errors
      - save_cache:
          key: v1-build-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths:
            - _build
            - deps
            - ~/.mix
      - persist_to_workspace:
          root: ~/
          paths:
            - guildatech
            - .mix

  test:
    working_directory: ~/guildatech
    environment:
      MIX_ENV: test
    docker:
      - image: cimg/elixir:1.11.3
      - image: circleci/postgres:11.5-alpine
    parallelism: 1
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: mix citest

  credo:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: credo
          command: mix credo --strict --ignore Credo.Check.Readability.MaxLineLength, Credo.Check.Consistency.SpaceAroundOperators

  format:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: format
          command: mix format --check-formatted

  sobelow:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: sobelow
          command: mix sobelow --config

  dialyzer:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-plt-cache-{{ checksum "mix.lock" }}
            - v1-plt-cache-{{ .Branch }}
            - v1-plt-cache
      - run: mix dialyzer --format short
      - save_cache:
          key: v1-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - "dialyzer.plt"
            - "dialyzer.plt.hash"
      - save_cache:
          key: v1-plt-cache-{{ .Branch }}
          paths:
            - "dialyzer.plt"
            - "dialyzer.plt.hash"

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test:
          requires:
            - build
      - credo:
          requires:
            - build
      - format:
          requires:
            - build
      - sobelow:
          requires:
            - build
